"use client"
import type { Metadata } from "next";
import { useState, useEffect } from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import Header from "@/app/Header/page"
import Footer from "@/app/footer/page"
import Carousel from "@/app/corousel/page"
import Form from "@/app/form/page"
import Question from "@/app/question/page"
import AOS from "aos";
import "aos/dist/aos.css";
import Script from "next/script";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,

}: Readonly<{
  children: React.ReactNode;

}>) {

  useEffect(() => {
  AOS.init({
    duration: 1000, // customize duration
    once: true,     // whether animation should happen only once
  });

  // Refresh AOS to recalculate positions
  AOS.refresh();
}, []);

  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
          rel="stylesheet"
        />
      </head>

      <body style={{ fontFamily: "'Poppins', sans-serif" }}>
     <Header/>

     
        {children}

      
        <div className="container-fluid mt-5 d-flex justify-content-center bg-dark"  style={{ height:"50vh" }}>
          <div className="text-center mt-5 py-5 rounded">
          <h1 className="fw-bold mb-4 text-white">Want to know more about London Book Publishers?</h1>
          <a href="/about-us/" className="btn btn-warning px-4 py-2">
            <i className="bi bi-info-circle me-2"></i> Learn More
          </a>
        </div>
      </div>



      <Carousel/>
      <Form/>
      <Question/>
      <Footer/>
      </body>
    </html>
  );
}
